name: growme
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  firebase_storage: ^13.0.4
  google_sign_in: ^6.1.0
  image_picker: ^1.0.1
  cloudinary_public: ^0.23.1
  intl: ^0.20.2
  fl_chart: ^1.1.1
  share_plus: ^11.0.0
  share_plus_platform_interface: ^6.1.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
