// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu07PnfyMPAoLx8gVRUfjq-AUux6cL0Ik',
    appId: '1:228418977294:web:0600c0908e96ac035d465f',
    messagingSenderId: '228418977294',
    projectId: 'growme-1',
    authDomain: 'growme-1.firebaseapp.com',
    storageBucket: 'growme-1.firebasestorage.app',
    measurementId: 'G-LE588Q32CF',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVV1zpYHTuZOKwxgIOA7j-b4NmXeDI3ts',
    appId: '1:228418977294:ios:0d5a996a1a9590c65d465f',
    messagingSenderId: '228418977294',
    projectId: 'growme-1',
    storageBucket: 'growme-1.firebasestorage.app',
    iosBundleId: 'com.example.growme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu07PnfyMPAoLx8gVRUfjq-AUux6cL0Ik',
    appId: '1:228418977294:web:5e2d27b983bdd3cb5d465f',
    messagingSenderId: '228418977294',
    projectId: 'growme-1',
    authDomain: 'growme-1.firebaseapp.com',
    storageBucket: 'growme-1.firebasestorage.app',
    measurementId: 'G-R65MNVVQR3',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVV1zpYHTuZOKwxgIOA7j-b4NmXeDI3ts',
    appId: '1:228418977294:ios:0d5a996a1a9590c65d465f',
    messagingSenderId: '228418977294',
    projectId: 'growme-1',
    storageBucket: 'growme-1.firebasestorage.app',
    iosBundleId: 'com.example.growme',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnJejKOfSCyEyAW-M9rzN6IiotBFHdbBQ',
    appId: '1:228418977294:android:5f1308ed31052f6d5d465f',
    messagingSenderId: '228418977294',
    projectId: 'growme-1',
    storageBucket: 'growme-1.firebasestorage.app',
  );

}